version: "3.8"
services:
  frontend:
    privileged: true
    tty: true
    working_dir: "/usr/share"
    build: /src/Frontend
    volumes:
      - "/dev:/dev:ro"
      - "InputFiles:/mnt/InputFiles"
      - "OutputFiles:/mnt/OutputFiles"
  backend:
    privileged: true
    tty: true
    working_dir: "/usr/share"
    build: /src/Backend
    volumes:
      - "/dev:/dev:ro"
      - "SharedDB:/mnt/SharedDB:ro"
      - "OutputFiles:/mnt/OutputFiles:ro"
  brain:
    privileged: true
    tty: true
    build: /src/Brain
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "SharedDB:/mnt/SharedDB"
      - "InputFiles:/mnt/InputFiles:ro"
      - "OutputFiles:/mnt/OutputFiles:ro"

volumes:
  InputFiles:
  OutputFiles:
  SharedDB: